services:
  - type: web
    name: telegram-games
    env: node
    rootDir: .
    buildCommand: npm run install-server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
